import type { Metadata } from 'next';
import { PublicLayout } from '@/src/app/layouts/PublicLayout';
import './globals.css';

export const metadata: Metadata = {
  title: 'Next Sneakers',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <PublicLayout>
          {children}
        </PublicLayout>
      </body>
    </html>
  );
}
