import type { Metadata } from 'next';
import { MainPage } from '@/src/pages/main';

export const metadata: Metadata = {
  title: 'Next Sneakers',
  description: 'Generated by create next app',
};

export default function Home() {
  return <MainPage />;
}
