import type { Metadata } from 'next';
import { MainPage } from '@/src/pages/main';

export const metadata: Metadata = {
  title: 'Next Sneakers',
  description: 'Generated by create next app',
};

export default async function Home(props: {
  searchParams?: Promise<{
    filter?: string;
    page?: number;
  }>;
}) {
  const searchParams = await props.searchParams;
  const filter = searchParams?.filter || '';
  const page = searchParams?.page || 1;

  return (
    <MainPage
      filter={filter}
      page={page}
    />
  );
}
